### ISSUE TITLE
Feature request: more stats

### ISSUE THREAD

**Issue by upbeat27** [MaJerle/lwmem#4]
Hi!
I found this memory allocator particularly intriguing due to its ability to allocate to many different memory regions.
One thing I find it is missing is more useful statistics.
It would be nice to be able to get this info from each LwMEM instance:
- Total memory size (yes, technically this could be obtained elsewhere, since you assigned the regions and their sizes)
- Most memory allocated since init (or least memory available since init)
- Currently allocated memory (or currently available memory)

These are helpful for determining heap usage over time and detecting leaks, etc.
It could of course be enabled/disabled via some #define, as the current stats are.
It would also be useful if it could be done on a region level vs. an instance level, so you can see if you need to decrease/increase the size of specific regions as you are developing the application.

**Comment by MaJerle** [comment]
> * Total memory size (yes, technically this could be obtained elsewhere, since you assigned the regions and their sizes)

That's something you can do today from region definition.

> * Most memory allocated since init (or least memory available since init)

That's currently not possible - you cannot find out *lowest ever memory still being available* in all regions

> * Currently allocated memory (or currently available memory)

That's available in the library actually - just not exposed to user. It is used to determine if there is at least being worth to scan regions to find free slot

> It would also be useful if it could be done on a region level vs. an instance level, so you can see if you need to decrease/increase the size of specific regions as you are developing the application.

Meaning of *region* is just to be able to define non-contingent block of data - there is no separate control block on each region. It is simple linked list that connects *available* blocks.

One option for you is then to enable multiple lwmem instances and each with single region.

**Comment by upbeat27** [comment]
Hi! Thanks for the quick response.

> > * Total memory size (yes, technically this could be obtained elsewhere, since you assigned the regions and their sizes)
> 
> That's something you can do today from region definition.

Yes, you can add up the region sizes yourself, but it could also be stored as a statistic in lwmem internally just for simplicity. Just an extra `size_t` when stats are enabled. Not as important, admittedly.


> 
> > * Most memory allocated since init (or least memory available since init)
> 
> That's currently not possible - you cannot find out _lowest ever memory still being available_ in all regions

Would it not just be a `size_t` that checks if `mem_available_bytes` is less than it (when something is alloc'd), and if so, it is set to `mem_available_bytes`? Equivalent to `xMinimumEverFreeBytesRemaining` in FreeRTOS heap.
Then you know the most amount of memory that has been used (or least amount of memory available) for that instance, since it was initialized.

> 
> > * Currently allocated memory (or currently available memory)
> 
> That's available in the library actually - just not exposed to user. It is used to determine if there is at least being worth to scan regions to find free slot

Yeah, I see it as `mem_available_bytes`. I am suggesting a way to access this, along with other stats, from the default and any other instances. Something like `lwmem_get_stats(lwmem_t* const lw, lwmem_stats_t* stats)`.
As is, the only stats are allocs/frees, and they can't be seen for the default instance.

> 
> > It would also be useful if it could be done on a region level vs. an instance level, so you can see if you need to decrease/increase the size of specific regions as you are developing the application.
> 
> Meaning of _region_ is just to be able to define non-contingent block of data - there is no separate control block on each region. It is simple linked list that connects _available_ blocks.
> 
> One option for you is then to enable multiple lwmem instances and each with single region.

OK, per region stats not possible, understood. Per instance is still extremely useful.

I can see about adding these and submitting a pull request.

**Comment by MaJerle** [comment]
> I can see about adding these and submitting a pull request.

Please go ahead. Makes sense to me.

Name stats function `lwmem_get_stats_ex(lwmem_t* const lw, lwmem_stats_t* stats)`, and then let's implement without `_ex` suffix for default instance.
