### ISSUE TITLE
error in lwmem.h

### ISSUE THREAD

**Issue by liuhao1946** [MaJerle/lwmem#6]
Hi, I think your library works fine，Thank you very much. However, there is a small error in lwmem.h at line 204.

The original definition
#define lwmem_get_size(ptr) lwmem_get_size(NULL, (ptr))

The correct definition
#define lwmem_get_size(ptr) lwmem_get_size_ex(NULL, (ptr))

**Comment by liuhao1946** [comment]
There is one more small problem. In lwmem.h, line 39 of the source code reads.
#include "lwmem/lwmem_opt.h"

As lwmem_opt.h is in the same directory as lwmem.h, it might be better to write it directly like this to prevent compilation path errors
#include "lwmem_opt.h"

**Comment by MaJerle** [comment]
> There is one more small problem. In lwmem.h, line 39 of the source code reads. #include "lwmem/lwmem_opt.h"
> 
> As lwmem_opt.h is in the same directory as lwmem.h, it might be better to write it directly like this to prevent compilation path errors #include "lwmem_opt.h"

It is expected that compiler sees path to `include` folder and then the rest resolves through relative paths.

**Comment by edieruby** [comment]
> Hi, I think your library works fine，Thank you very much. However, there is a small error in lwmem.h at line 204.
> 
> The original definition #define lwmem_get_size(ptr) lwmem_get_size(NULL, (ptr))
> 
> The correct definition #define lwmem_get_size(ptr) lwmem_get_size_ex(NULL, (ptr))

This error is fixed in develop branch.
Is there a plan to release a version in main branch?

**Comment by MaJerle** [comment]
https://github.com/MaJerle/lwmem/releases/tag/v2.1.0
