### ISSUE TITLE
Warning with LWMEM_CFG_CLEAN_MEMORY and accompanying LWMEM_MEMSET call

### ISSUE THREAD

**Issue by SuppenSeebi** [MaJerle/lwmem#8]
**Problem:**
If user option _LWMEM_CFG_CLEAN_MEMORY_ is enabled (set to 1) there will be a memset-call inside _prv_insert_free_block_ which will clean the free-ed blocks with zeros. Inside this memset-call is a macro, which either returns a block pointer or _NULL_, where the latter throws a compiler warning _-Wnonull_ for the memset-call.

See the following code snippets of lwmem.c:
```C
111: #define LWMEM_GET_PTR_FROM_BLOCK(block) (void *)((block) != NULL ? ((LWMEM_TO_BYTE_PTR(block)) + LWMEM_BLOCK_META_SIZE) : NULL)

219: /* Check valid inputs */
220: if (nb == NULL) {
221:    return;
222: }

248: LWMEM_MEMSET(LWMEM_GET_PTR_FROM_BLOCK(nb), 0x00, nb->size - LWMEM_BLOCK_META_SIZE);
```
Compiler-warning:
_null argument where non-null required (argument 1) [-Wnonnull]_

**Proposal for fix:**
In this function nb is already checked for not beeing _NULL_, so the used macro itself does not need to do this again. As a fix for removing this warning I propose a second define, similar to _LWMEM_GET_PTR_FROM_BLOCK_, which does not check the input for beeing _NULL_ but rather just returns the block. This macro should only be called, if _nb_ is checked for beeing _NULL_ earlier! My proposal code would look like this:

New macro definition:
```C
/**
 * \brief           Get block handle from application pointer. Is not NULL-ptr safe! User must check for NULL pointers in advance to this call! Otherwise use @LWMEM_GET_PTR_FROM_BLOCK
 * \param[in]       block: Input pointer to get block from
 */
#define LWMEM_GET_PTR_FROM_BLOCK_UNSAFE(block) (void *)((LWMEM_TO_BYTE_PTR(block)) + LWMEM_BLOCK_META_SIZE)
```

Updated memset call:
```C
248: LWMEM_MEMSET(LWMEM_GET_PTR_FROM_BLOCK_UNSAFE(nb), 0x00, nb->size - LWMEM_BLOCK_META_SIZE);
```

**Comment by SuppenSeebi** [comment]
Yes, this is a false-positive and just a suggestion form my side. I will most likely use your lwmem in my masters thesis. For this i will need warning free code, since it is external code. I'm totally fine with your decission of not updating it, if you decide so. I see it the same way as you do.
I can do local changes to the code myself to fix this problem (and the problem I issued before), so no worries! :)

**Comment by MaJerle** [comment]
> Yes, this is a false-positive and just a suggestion form my side. I will most likely use your lwmem in my masters thesis. For this i will need warning free code, since it is external code. I'm totally fine with your decission of not updating it, if you decide so. I see it the same way as you do. I can do local changes to the code myself to fix this problem (and the problem I issued before), so no worries! :)

Your thesis should provide the information clarifying why there is warning :)
